services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  pocketbase:
    image: elestio/pocketbase
    restart: unless-stopped
    volumes:
      - pb_data:/pb_data
    expose:
      - "8090"

  monitor:
    image: henrygd/beszel
    restart: unless-stopped
    expose:
      - "8090"

  metrics:
    image: victoriametrics/victoria-metrics:latest
    restart: unless-stopped
    volumes:
      - vm_data:/victoria-metrics-data
    command:
      - '--storageDataPath=/victoria-metrics-data'
      - '--httpListenAddr=:8428'
    expose:
      - "8428"

  logs:
    image: victoriametrics/victoria-logs:latest
    restart: unless-stopped
    volumes:
      - vl_data:/victoria-logs-data
    command:
      - '--storageDataPath=/victoria-logs-data'
    expose:
      - "9428"

volumes:
  caddy_data:
  caddy_config:
  pb_data:
  vm_data:
  vl_data: